server:
  port: 8090

keycloak:
  realm: "pet"
  auth-server-url: https://javaforall.tech/oauth/auth
  ssl-required: external
  resource: "pet-service"
  credentials:
    secret: 3366cef5-3f26-45bc-84c4-fc22f7b73050
  use-resource-role-mappings: true
  bearer-only: true

